preset: laravel

disabled:
  - alpha_ordered_imports
  - concat_without_spaces

enabled:
  - phpdoc_order
  - phpdoc_property
  - phpdoc_separation
  - concat_with_spaces
  - length_ordered_imports
  - phpdoc_add_missing_param_annotation
